"""Generate prompt_template_seed.sql from the constants in supervisor_prompt_builder.py.

Run:  python3 generate_template_seed.py > prompt_template_seed.sql

Why a generator instead of a hand-written SQL file: the inline fallback prompt
and the template row must say the same thing, otherwise an A/B between
`prompt_source = inline` and `prompt_source = template` measures wording drift
instead of methodology. Both read SUPERVISOR_METHODOLOGY / SUPERVISOR_OUTPUT_CONTRACT.

Variable names below are the exact keys returned by
`trade_runtime/prompting/render_context_builder.build_supervisor_render_context`.
`sizing_constraints_json` is NOT produced by that function today - see
README section "Render-context patch". Without the patch the template path
would silently lose the sizing block the inline prompt has.
"""

from __future__ import annotations

import importlib.util
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("builder", HERE / "supervisor_prompt_builder.py")
builder = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(builder)

TEMPLATE_CODE = "SUPERVISOR_ENTRY_DISCIPLINE_V1"
TEMPLATE_NAME = "Supervisor - entry discipline (location / regime / RR gates) v1"

CONTEXT_SECTION = """PREVIOUS SUPERVISOR DECISIONS
{previous_supervisor_decisions_json}

LONG-TERM EXPERIENCE MEMORY
{long_term_memory_json}

MEMORY USAGE
{memory_usage_json}

DECISION CONTEXT
symbol: {symbol}
exchange: {exchange}
event_strength: {event_strength}
trace_id: {trace_id}
current_time: {current_time}
account_equity: {account_equity}
daily_pnl: {daily_pnl}
current_position_side: {current_position_side}
current_position_quantity: {current_position_quantity}
current_position_notional: {current_position_notional}
current_position_opened_at: {current_position_opened_at}
current_position_holding_minutes: {current_position_holding_minutes}
market_source_status: {market_source_status}

risk_limits: {runtime_risk_limits_json}
sizing_constraints: {sizing_constraints_json}
market_context: {market_context_json}
market_source_context: {market_source_context_json}
position_risk_context: {position_risk_context_json}
strategy_context: {strategy_context_json}
recent_news_context: {recent_news_context_json}
recent_onchain_context: {recent_onchain_context_json}
market_view: {market_view_json}
news_view: {news_view_json}
onchain_view: {onchain_view_json}
social_view: {social_view_json}
agent_messages: {agent_messages_json}
deliberation_summary: {deliberation_summary}
deliberation_referee_review: {deliberation_referee_review_json}
short_term_memory: {short_term_memory_json}"""

VARIABLES = [
    "previous_supervisor_decisions_json",
    "long_term_memory_json",
    "memory_usage_json",
    "symbol",
    "exchange",
    "event_strength",
    "trace_id",
    "current_time",
    "account_equity",
    "daily_pnl",
    "current_position_side",
    "current_position_quantity",
    "current_position_notional",
    "current_position_opened_at",
    "current_position_holding_minutes",
    "market_source_status",
    "runtime_risk_limits_json",
    "sizing_constraints_json",
    "market_context_json",
    "market_source_context_json",
    "position_risk_context_json",
    "strategy_context_json",
    "recent_news_context_json",
    "recent_onchain_context_json",
    "market_view_json",
    "news_view_json",
    "onchain_view_json",
    "social_view_json",
    "agent_messages_json",
    "deliberation_summary",
    "deliberation_referee_review_json",
    "short_term_memory_json",
]


def sql_str(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def main() -> None:
    content = f"{builder.SUPERVISOR_METHODOLOGY}\n\n{builder.SUPERVISOR_OUTPUT_CONTRACT}\n\n{CONTEXT_SECTION}"
    assert "{" not in builder.SUPERVISOR_METHODOLOGY and "}" not in builder.SUPERVISOR_METHODOLOGY
    assert "{" not in builder.SUPERVISOR_OUTPUT_CONTRACT and "}" not in builder.SUPERVISOR_OUTPUT_CONTRACT
    variables_csv = ",".join(VARIABLES)
    # `variables` column is varchar(255); the full list does not fit, so keep
    # the column as a pointer and rely on content. Verify length here.
    variables_col = variables_csv if len(variables_csv) <= 255 else "see_content_placeholders"

    out: list[str] = []
    out.append("-- Generated by generate_template_seed.py. Do not hand-edit; edit supervisor_prompt_builder.py.")
    out.append("-- Target: MySQL (RuoYi). Tables prompt_template / trade_prompt_binding.")
    out.append("")
    out.append("-- 1) Retire any previous default supervisor template so the new one is unambiguous.")
    out.append("UPDATE prompt_template SET is_default = 0, update_by = 'handoff', update_time = NOW()")
    out.append(f"  WHERE code <> {sql_str(TEMPLATE_CODE)} AND is_default = 1;")
    out.append("")
    out.append("-- 2) Upsert the methodology template.")
    out.append("INSERT INTO prompt_template (code, name, content, variables, version, is_active, is_default, remark, create_by, create_time, update_by, update_time)")
    out.append("VALUES (")
    out.append(f"  {sql_str(TEMPLATE_CODE)},")
    out.append(f"  {sql_str(TEMPLATE_NAME)},")
    out.append(f"  {sql_str(content)},")
    out.append(f"  {sql_str(variables_col)},")
    out.append("  1, 1, 1,")
    out.append(
        "  "
        + sql_str(
            "Task 1+3 of the 7-day review hand-off. Adds location / regime / reward-to-risk gates; "
            "keeps the JSON output contract byte-compatible with the risk gate. Content must not contain "
            "literal curly braces (renderer substitutes every {name}). Requires sizing_constraints_json in "
            "build_supervisor_render_context."
        )
        + ","
    )
    out.append("  'handoff', NOW(), 'handoff', NOW()")
    out.append(")")
    out.append("ON DUPLICATE KEY UPDATE")
    out.append("  name = VALUES(name), content = VALUES(content), variables = VALUES(variables),")
    out.append("  version = version + 1, is_active = 1, is_default = 1, remark = VALUES(remark),")
    out.append("  update_by = 'handoff', update_time = NOW();")
    out.append("")
    out.append("-- 3) Bind it to the supervisor for every mode / event strength (empty scope JSON = match all).")
    out.append("--    No strategy / symbol scoping so it is the global default; add narrower rows later for A/B.")
    out.append("INSERT INTO trade_prompt_binding (binding_name, strategy_id, strategy_version_id, symbol, exchange_code, binding_scope,")
    out.append("  template_code, fallback_template_code, model_id, output_schema_code, priority, mode_scope_json,")
    out.append("  event_strength_scope_json, enabled, remark, created_at, updated_at)")
    out.append("SELECT 'supervisor-entry-discipline-global', NULL, NULL, NULL, NULL, 'SUPERVISOR',")
    out.append(f"  {sql_str(TEMPLATE_CODE)}, NULL, NULL, NULL, 100, '[]', '[]', 1,")
    out.append("  'Global supervisor binding from the 7-day review hand-off. Lower priority number wins in prompt_binding_resolver.',")
    out.append("  NOW(), NOW()")
    out.append("WHERE NOT EXISTS (")
    out.append("  SELECT 1 FROM trade_prompt_binding WHERE binding_scope = 'SUPERVISOR' AND template_code = " + sql_str(TEMPLATE_CODE))
    out.append(");")
    out.append("")
    out.append("-- 4) Verification (run after the worker has made at least one decision):")
    out.append("-- SELECT prompt_source, resolved_template_code, COUNT(*) FROM decision_run")
    out.append("--   WHERE create_time > NOW() - INTERVAL 1 HOUR GROUP BY 1, 2;")
    out.append("-- Expected: prompt_source = 'template', resolved_template_code = '" + TEMPLATE_CODE + "'.")
    out.append("-- If it still says 'inline', check: prompt_template.is_active = 1, GET /dca/template/code/" + TEMPLATE_CODE)
    out.append("--   returns the row, and the worker's registry cache was restarted.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
